version: 0.0
os: linux
files:
  - source: /
    destination: /folders/exe/$APPLICATION_NAME
  - source: /package.json
    destination: /folders/configs/
  - source: /package.json
    destination: /folders/logs/$APPLICATION_NAME
permissions:
  - object: /folders/exe/$APPLICATION_NAME
    owner: ec2-user
    mode: 744
    group: ec2-user
  #   # type:
  #   #   - file
hooks:
  BeforeInstall:
    - location: /scripts/install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /scripts/reload.sh
      timeout: 180
      runas: ec2-user
